baseURL = "https://jeas.io/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Jeas - Programmes en Python"
enableRobotsTXT = true
theme = "aether"


[params]
    brand = "jeas.io"
    description = "Programmes en langage Python avec NumPy et Matplotlib. Pi, méthode de Monte-Carlo, stéganographie."
    #bgimg = "img/hip-square.png"
    bgimg = "img/pink_rice.png"
    #bgimg = "img/vintage-concrete.png"
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "pygments" # vs pastie monokailight bw arduino igor tango emacs manni perldoc murphy rainbow_dash xcode
    tabWidth = 4
