baseURL = "https://jeaspy.netlify.app/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = "Jeaspy - Programmes en Python"

theme = "aether"


[params]
    description = "Programmes en langage Python avec NumPy et Matplotlib. Pi, méthode de Monte-Carlo, stéganographie."
    #bgimg = "img/hip-square.png"
    bgimg = "img/pink_rice.png"
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "pygments" # vs pastie monokailight bw arduino igor tango emacs manni perldoc murphy rainbow_dash xcode
    tabWidth = 4
